Feature/subscribe modal
TanyaJulieva/project-CodeLovers23 pull request #11
Opened 2023-06-04 01:17 UTC by PVjacheslav

Прохання подивитись модалку, НЕ ПРИЙМАТИ, поки все не запрацює!
Питання: 1. чи підключеній скріпт java script "modal"? (кнопки відкриття і закриття модалки не працюють)
                2. іконки так і не зявились може не завантажена у sprite? (не відображається svg закриття модалки)

2023-06-04 12:01 UTC, TanyaJulieva requested changes

2023-06-04 18:00 UTC, VarshavetsAleksandr commented on src/partials/pop-up-explore.html
Не працює ретінізація та картинка не змінюється на різних екранах

2023-06-04 18:03 UTC, VarshavetsAleksandr commented on src/css/pop-up-explore.css
> +  padding: 26px 24px 32px;
По макету padding: 32px 24px;

2023-06-04 19:27 UTC, PVjacheslav commented on src/partials/pop-up-explore.html
>        </svg>
done

2023-06-04 19:27 UTC, PVjacheslav commented on src/partials/pop-up-explore.html
> +          <button class="modal-explore-btn" type="submit">Submit</button>
done

2023-06-04 19:28 UTC, PVjacheslav commented on src/css/pop-up-explore.css
>    background-color: #fafafa;
done

2023-06-04 19:28 UTC, PVjacheslav commented on src/css/pop-up-explore.css
> +  padding-top: 6px;
done

2023-06-04 19:30 UTC, PVjacheslav commented on src/css/pop-up-explore.css
> +  padding: 26px 24px 32px;
done

2023-06-05 07:33 UTC, PVjacheslav commented on src/partials/pop-up-explore.html
done

2023-06-05 12:58 UTC, TanyaJulieva approved these changes

2023-06-05 12:59 UTC, merged