Feature/header
TanyaJulieva/project-CodeLovers23 pull request #16
Opened 2023-06-04 12:49 UTC by 14051978

Іконки соц сітей взагалі не відображаються (

2023-06-04 20:58 UTC, arteeeemt commented on src/partials/header.html
> +            <svg class="icon-logo" width="21" height="21">
на макеті width="24" height="24")

2023-06-04 21:03 UTC, arteeeemt commented on src/partials/header.html
> +            <svg class="icon-logo" width="21" height="21">
за макетом width="24" height=''24''

2023-06-04 21:05 UTC, arteeeemt commented on src/partials/header.html
> +        <use href="../img/icons.svg/#instagram"></use>
за макетом width 24 height 24

2023-06-04 21:05 UTC, arteeeemt commented on src/partials/header.html
> +                    <svg class="social-icon" width="32" height="32">
за макетом width 24 height 24

2023-06-05 07:50 UTC, TanyaJulieva requested changes

2023-06-05 07:50 UTC, TanyaJulieva commented on src/css/header.css
> +    padding-left: 32px;
тут, мабуть, і padding-right: 32.
але це прописано в загальних стилях, можете це не вказувати

2023-06-05 07:50 UTC, TanyaJulieva commented on src/css/header.css
> +    padding-right:9px ;
бокові падінги прописані в загальних стилях

2023-06-05 07:50 UTC, TanyaJulieva commented on src/css/header.css
> +    background-color:var(--light-bg-color);
бекграунд задан для боді

2023-06-05 07:50 UTC, TanyaJulieva commented on src/css/header.css
> +    align-items: center;
align-items: center; це Ви прописали в .header-container, тут не потрібне

2023-06-05 07:50 UTC, TanyaJulieva commented on src/css/mobile-menu.css
> +    padding-top: 20px;
[padding-top: 20px, мабуть, не треба

2023-06-05 09:09 UTC, 14051978 commented on src/partials/header.html
> +        <use href="../img/icons.svg/#instagram"></use>
Виправлено )

2023-06-05 11:10 UTC, TanyaJulieva approved these changes

2023-06-05 11:12 UTC, merged