add footer.html and footer.css
TanyaJulieva/project-CodeLovers23 pull request #3
Opened 2023-06-02 12:17 UTC by VarshavetsAleksandr

Було додано розмітка footer.htm та footer.css стилі

2023-06-03 10:23 UTC, TanyaJulieva requested changes

2023-06-03 10:23 UTC, TanyaJulieva commented on src/css/footer.css
> +    margin-bottom: 32px;
може, тут паддінг-боттом 32 для .footer-wrapper? в .footer-thumb же сусіднього елемента

@media only screen and (min-width: 768px) {
    .footer-wrapper {
        padding-bottom: 50px;
    }
}

@media only screen and (min-width: 1200px) {
    .footer-wrapper {
        padding-bottom: 58px;
    }
}

2023-06-03 10:23 UTC, TanyaJulieva commented on src/css/footer.css
> +.footer-social-icon {}
додаси?)

2023-06-03 10:23 UTC, TanyaJulieva commented on src/css/footer.css
> +    row-gap: 18px;
мабуть, тут просто gap: 18px, а в медіа змінюється flex-direction на row і gap на 24px
бо якщо в тебе не сітка, а просто колонка, то навіщо тут  column-gap?)

2023-06-03 22:23 UTC, VarshavetsAleksandr commented on src/css/footer.css
> +.footer-container {}
.footer-container  - класс має аналог - container. У класі container - задані медіаправило для адаптивної верстки з падінгами

2023-06-03 22:24 UTC, VarshavetsAleksandr commented on src/css/footer.css
> +    margin-bottom: 32px;
Виправлено .

2023-06-03 22:25 UTC, VarshavetsAleksandr commented on src/css/footer.css
> +    row-gap: 18px;
Тут без різниці, якщо в нас немає row-gap (горизонтального відступу) він не буде доданий.

2023-06-03 22:29 UTC, VarshavetsAleksandr commented on src/css/footer.css
> +.footer-social-icon {}
Тут не розумію що треба додати, відпиши в телеграм будь-ласка

2023-06-03 22:42 UTC, VarshavetsAleksandr commented on src/css/footer.css
> +.footer-container {}
Стилі для container прописані в файлі reset.css

2023-06-04 07:08 UTC, TanyaJulieva approved these changes

2023-06-04 07:08 UTC, merged